- name: setup-host | Install Common Packages
  ansible.builtin.package:
    name: "{{ common_packages[ansible_os_family] }}"
    state: latest
    update_cache: yes

- name: setup-host | Disable swap
  ansible.builtin.command: swapoff -a

- name: setup-host | Remove swap entry from /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: 'swap'
    state: absent

- name: setup-host | Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd

- name: setup-host | Prepare hosts entry
  ansible.builtin.shell: |
    for h in {{ ansible_play_hosts|join(' ') }};do
      ip=$(ansible-inventory -i {{ inventory_file }} --host $h|jq .ansible_host|sed -e 's/\"//g')
      echo "$ip $h"
    done
  delegate_to: localhost
  register: _hosts_entry
  run_once: true

- name: setup-host | Show hosts entry
  ansible.builtin.debug:
    var: _hosts_entry.stdout_lines
  run_once: true

- name: setup-host | Add _hosts_entry in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^{{ item.split(' ')[0] }}"
    line: '{{ item }}'
  with_items: "{{ _hosts_entry.stdout_lines }}"

# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
# Red Hat-based distributions -> Set SELinux to permissive mode:
- name: setup-host | Set selinux to permission mode
  ansible.builtin.command: setenforce 0
  when: ansible_os_family == "RedHat"

- name: setup-host | Set permissive in /etc/selinux/config
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX'
    line: 'SELINUX=permissive'
  when: ansible_os_family == "RedHat"
