# Install calicoctl as kubectl plugin
- name: calicoctl | Install calicoctl as kubectl plugin
  ansible.builtin.get_url:
    url: "{{ calicoctl_url }}"
    dest: /usr/bin/kubectl-calico
    mode: '0755'
  tags:
  - calicoctl
  - calico
