---

# Install calicoctl as kubectl plugin
- name: Install kubectl-calico
  ansible.builtin.get_url:
    url: https://github.com/projectcalico/calico/releases/latest/download/calicoctl-linux-amd64
    dest: /usr/bin/kubectl-calico
    mode: 0755
  tags:
      - calicoctl
      - calico
  become: true


