- name: calico | Download Calico manifest config for {{ calico_version }}
  ansible.builtin.get_url:
    url: "{{ calico_install_method['manifest']['config']['url'] }}"
    dest: "/var/tmp/{{ calico_install_method['manifest']['config']['local_file'] }}"
    mode: '0644'

- name: calico | Apply Calico manifest config
  ansible.builtin.command: kubectl apply -f /var/tmp/{{ calico_install_method['manifest']['config']['local_file'] }}
  environment:
    KUBECONFIG: "{{ KUBECONFIG }}"

- name: calico | Wait for calico to come up
  ansible.builtin.pause:
    echo: yes
    minutes: 5
