- name: kubeconfig | Create .kube
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.kube"
    state: directory
  delegate_to: localhost
  become: false

- name: kubeconfig | Fetch kubeconfig from master to localhost
  ansible.builtin.fetch:
    src: "{{ KUBECONFIG }}"
    dest: "{{ LOCAL_KUBECONFIG }}"
    flat: yes
    mode: '0644'

- name: kubeconfig | Run reachability test
  ansible.builtin.command: kubectl get nodes
  register: _kstatus
  environment:
    KUBECONFIG: "{{ LOCAL_KUBECONFIG }}"
  delegate_to: localhost
  become: false
  changed_when: false
  failed_when: _kstatus.rc != 0
