---
- hosts: master
  gather_facts: true
  become: yes

  pre_tasks:
  - name: Check stat of kube config on localhost
    ansible.builtin.stat:
      path: "{{lookup('env', 'HOME')}}/.kube/config"
    delegate_to: localhost
    register: _local_kconfig

  roles:
  - role: download-kubeconfig
    when: not _local_kconfig.stat.exists