---

- hosts: all
  gather_facts: true
  become: true

  tasks:
  - name: Install google cloud public signing key
    ansible.builtin.shell: curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
    when: ansible_distribution == "Ubuntu"

  - name: Add kubernetes apt key
    ansible.builtin.shell: echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
    when: ansible_distribution == "Ubuntu"

  - name: Install Packages on Ubuntu
    ansible.builtin.apt:
      name:
        - kubectl
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  