---
- hosts: localhost
  gather_facts: false

  vars:
    apps_list:
      - 'nginx'
  
  pre_tasks:
  - name: Check stat of kube config on localhost
    ansible.builtin.stat:
      path: "{{lookup('env', 'HOME')}}/.kube/config"
    delegate_to: localhost
    register: _local_kconfig

  - name: Run asserts
    ansible.builtin.assert:
      that:
        - app is defined and app in apps_list
        - _local_kconfig.stat.exists
      fail_msg:
        - "'app' must be defined and app must be in {{apps_list}}"
        - "If you do not have kubeconfig on localhost. Check [Download kubeconfig on localhost] in README"

  roles:
  - role: applications-example/nginx-web
    when: app == 'nginx'

