---

- hosts: all:!worker
  gather_facts: true
  become: "{{become_root|default('yes')}}"

  vars:
    
  tasks:
  - name: Install MetalLB
    ansible.builtin.include_role:
      name: metallb
      tasks_from: main.yml
    tags:
      - metallb