---

- name: Run Playbook to Download KubeConfig
  hosts: master
  gather_facts: true

  pre_tasks:
  - name: kubeconfig | Check stat of kube config on localhost
    ansible.builtin.stat:
      path: "{{ LOCAL_KUBECONFIG }}"
    delegate_to: localhost
    register: _local_kconfig

  tasks:
  - name: kubeconfig | Include download-kubeconfig role
    include_role:
      name: download-kubeconfig
