---

- hosts: all
  gather_facts: true
  
  tasks:
  # - name: Run role setup-host
  #   ansible.builtin.include_role:
  #     name: setup-host

  # - name: Run role container-runtime
  #   ansible.builtin.include_role:
  #     name: container-runtime
  
  # - name: Install minikube
  #   ansible.builtin.include_role:
  #     name: minikube

  - name: Include kubectl tasks
    ansible.builtin.include_role:
      name: k8s-tools
      tasks_from: kubectl.yml

# - ansible.builtin.import_playbook: common/cni-provider.yml
#   vars:
#     cni_provider: calico
#     KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"
#     become_root: no
