apiVersion: v1
kind: ConfigMap
metadata:
  name: pdns-config
  namespace: powerdns
data:
  pdns.conf: |
    launch=gmysql

    gmysql-host=powerdns-mariadb
    gmysql-user=powerdns
    gmysql-password=pdnspass
    gmysql-dbname=powerdns

    api=yes
    api-key=supersecretapikey

    webserver=yes
    webserver-address=0.0.0.0
    webserver-port=8081

    local-address=0.0.0.0
    local-port=53

    loglevel=5
    log-dns-queries=yes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: powerdns-auth
  namespace: powerdns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: powerdns-auth
  template:
    metadata:
      labels:
        app: powerdns-auth
    spec:
      containers:
      - name: pdns
        image: powerdns/pdns-auth-48
        command: ["pdns_server"]
        args:
        - --config-dir=/etc/pdns-clean
        - --local-port=5353
        # - --launch=gmysql
        # - --gmysql-host=powerdns-mariadb
        # - --gmysql-user=powerdns
        # - --gmysql-password=pdnspass
        # - --gmysql-dbname=powerdns
        # - --api=yes
        # - --api-key=supersecretapikey
        # - --webserver=yes
        # - --webserver-address=0.0.0.0
        # - --webserver-port=8081
        volumeMounts:
        - name: pdns-config
          mountPath: /etc/pdns-clean/pdns.conf
          subPath: pdns.conf
        ports:
        - containerPort: 5353
          protocol: UDP
        - containerPort: 5353
          protocol: TCP
        - containerPort: 8081
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE        
      volumes:
      - name: pdns-config
        configMap:
          name: pdns-config

---
apiVersion: v1
kind: Service
metadata:
  name: powerdns-auth
  namespace: powerdns
spec:
  selector:
    app: powerdns-auth
  ports:
  - name: dns-udp
    port: 53
    targetPort: 5353
    protocol: UDP
  - name: dns-tcp
    port: 53
    targetPort: 5353
    protocol: TCP
  - name: api
    port: 8081
    targetPort: 8081