docker_repo:
  RedHat: "https://download.docker.com/linux/centos/docker-ce.repo"

containerd_packages:
  Ubuntu:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
  RedHat:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin
