---

- hosts: all
  gather_facts: true
  become: true
  roles:
  - role: setup-host
  - role: container-runtime

- ansible.builtin.import_playbook: common/install-kubectl.yml

- hosts: all
  gather_facts: true
  become: true
  roles:
  - role: minikube

- ansible.builtin.import_playbook: common/cni-provider.yml
  vars:
    cni_provider: calico
    KUBECONFIG: "/home/{{ansible_user}}/.kube/config"
    become_root: no
  

