# Deploy and publish nginx using Ingress Backed by NodePort Service
apiVersion: v1
kind: Namespace
metadata:
  name: hello-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hello-ns
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: hello-ns
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nginx-ing
#   namespace: nginx-ns
#   annotations:
# spec:
#   ingressClassName: nginx
#   rules:
#   - host: demo.quasarstack.com
#     http:
#       paths:
#       - pathType: Prefix
#         path: "/"
#         backend:
#           service:
#             name: nginx-service
#             port:
#               number: 80
